### PR TITLE
Revert "Update primary.txt"

### PR DESCRIPTION
**Pull request by MTanwirS**
Reverts prathibha27/colors#5

### CODE REVIEW

**Comment by MTanwirS** [comment]
Saaku
Enu kelsa madilla

**Comment by MTanwirS** [comment]
BYE

**Comment by prathibha27** [comment]
bye bye ##

**Comment by MTanwirS** [comment]
being a good coder is to recognise mistakes
so reverting my changes makes me a better coder to improve your stupid code
thank you

**Comment by MTanwirS** [comment]
*mic drop.
YOU cant comment on this anymore 
#3  colours are not boring you may be ?
download

**Comment by prathibha27** [comment]
god bless you child

**Pull request closed without merging**
