### PR TITLE
Update primary.txt

### PR DESCRIPTION
**Pull request by MTanwirS**
Comment

### CODE REVIEW

**Comment by prathibha27** [comment]
hey your commit is stupid

**Comment by MTanwirS** [comment]
> Comment



> Comment

your code's even stupider

**Comment by MTanwirS** [comment]
hahahahahahah

**Comment by prathibha27** [comment]
awhhh really , and you are forking the same XD

**Comment by MTanwirS** [comment]
dont comment anyhting now.

**Comment by MTanwirS** [comment]
yes coz am stupid

**Comment by prathibha27** [comment]
known facts

**Comment by MTanwirS** [comment]
stupids learn stupidity from greater stupids

**Comment by MTanwirS** [comment]
True

**Comment by prathibha27** [comment]
wah wah modern day plato

**Comment by MTanwirS** [comment]
whose pluto

**Comment by prathibha27** [comment]
its plato not pluto

**Comment by MTanwirS** [comment]
what butler english its plate not plato platu

**Comment by prathibha27** [comment]
you need google my friend

**Comment by MTanwirS** [comment]
Naane google
use Binng.com by YAhoo

**Comment by prathibha27** [comment]
-_-

**Pull request merged**
